package_name: devassistant
version: 0.10.0dev
license: GPLv2+
authors: [Bohuslav Kabrda <bkabrda@redhat.com>]
homepage: https://github.com/devassistant/dap-devassistant
summary: DevAssistant prep assistants to develop DevAssistant itself
bugreports: https://github.com/devassistant/dap-devassistant/issues
dependencies:
  - common_args
  - python
description: |
    Set up environment for DevAssistant, so you can develop on DevAssistant trough DevAssistant. We have to go deeper.
